tasks:
  - name: Initialize React.js App
    command: |
      cd Clone_Facebook
      npm install
      npm run start

  - name: Initialize Backend   
    command: |
      cd Clone_Facebook_Backend
      npm install
      npm run dev
