tasks:
  - name: Initialize React.js App
    command: |
      cd Clone_Facebook
      npm install
      npm run start
      cd ..

  - name: Initialize Backend   
    command: |
      cd Clone_Facebook_Backend
      npm i
      npm run dev
      cd ..